Repository WildCodeSchool-2024-09/JS-RemoteFR-Crew404-Mathemagie, pull requests merged in 2025-01, with the labels that each got.

#2 S03 us07 games
  client/src/App.css
  client/src/App.tsx
  client/src/components/GamesHome.css
  client/src/components/GamesHome.tsx
  client/src/main.tsx
Labels: REVIEWD

#4 S03 us06 inscription
  client/src/App.css
  client/src/App.tsx
  client/src/assets/images/batman.png
  client/src/assets/images/superH.webp
  client/src/components/AuthPage.css
  client/src/components/AuthPage.tsx
  client/src/components/ForgotPassword.css
  client/src/components/ForgotPassword.tsx
  client/src/components/LoginForm.css
  client/src/components/LoginForm.tsx
  client/src/components/SignUpForm.css
  client/src/components/SignUpForm.tsx
  client/src/index.css
  client/src/main.tsx
Labels: CONFLICTS_RESOLVED, REVIEWD

#5 S03 us09 avatar
  client/index.html
  client/public/avatarphotos/cadenas.png
  client/public/avatarphotos/chat.png
  client/public/avatarphotos/chien.png
  client/public/avatarphotos/renard.png
  client/public/logo.png
  client/src/App.tsx
  client/src/main.tsx
  client/src/pages/Avatar/Avatar.tsx
  client/src/pages/Avatar/avatar.css
  client/src/pages/Avatar/components
Labels: REVIEWD

#3 S03 us08 page404
  client/src/App.css
  client/src/App.tsx
  client/src/assets/images/404bcg.jpg
  client/src/assets/images/404notfound.jpg
  client/src/assets/images/logoM.png
  client/src/components/Home.css
  client/src/components/Home.tsx
  client/src/components/LoginForm.tsx
  client/src/main.tsx
  client/src/pages/NotFound.css
  client/src/pages/NotFound.tsx
Labels: REVIEWD

#10 S04 us12 creation game partie1
  client/src/App.tsx
  client/src/main.tsx
  client/src/pages/NumGame.css
  client/src/pages/NumGame.tsx
Labels: CORRECTIONS_DONE

#11 S04 us13 creation jeu 2
  client/index.html
  client/src/App.tsx
  client/src/main.tsx
  client/src/pages/GameOne/GameOne.css
  client/src/pages/GameOne/GameOne.tsx
Labels: REVIEWD

#7 Ajout du jeu 1
  client/src/App.tsx
  client/src/assets/images/car.png
  client/src/components/CarGame.css
  client/src/components/CarGame.tsx
  client/src/main.tsx
  package-lock.json
Labels: CHANGE_REQUESTED

#14 S04 us12 creation game partie1
  client/src/App.tsx
  client/src/main.tsx
  client/src/pages/Auth/AuthPage.css
  client/src/pages/Auth/AuthPage.tsx
  client/src/pages/ForgotPassword/ForgotPassword.css
  client/src/pages/ForgotPassword/ForgotPassword.tsx
  client/src/pages/GamesHome/GamesHome.css
  client/src/pages/GamesHome/GamesHome.tsx
  client/src/pages/Home/Home.css
  client/src/pages/Home/Home.tsx
  client/src/pages/LevelGame1/LevelGame1.css
  client/src/pages/LevelGame1/LevelGame1.tsx
  client/src/pages/LoginForm/LoginForm.css
  client/src/pages/LoginForm/LoginForm.tsx
  client/src/pages/Notfound/NotFound.css
  client/src/pages/Notfound/NotFound.tsx
  client/src/pages/NumGame/NumGame.css
  client/src/pages/NumGame/NumGame.tsx
  client/src/pages/SignUpForm/SignUpForm.css
  client/src/pages/SignUpForm/SignUpForm.tsx
Labels: REVIEWD

#15 fixing index
  client/index.html
  client/public/avatarphotos/CAT.png
  client/public/avatarphotos/FOX.png
  client/public/avatarphotos/TIGER.png
  client/public/avatarphotos/chat.png
  client/public/avatarphotos/chien.png
  client/public/avatarphotos/elephant.png
  client/public/avatarphotos/renard.png
  client/src/App.tsx
  client/src/pages/Avatar/Avatar.tsx
  client/src/pages/Avatar/avatar.css
Labels: REVIEWD

#18 S06 us fix css
  client/src/App.css
  client/src/App.tsx
  client/src/main.tsx
  client/src/pages/GamesHome/GamesHome.css
  client/src/pages/GamesHome/GamesHome.tsx
  client/src/pages/Home/Home.css
  client/src/pages/Home/Home.tsx
Labels: REVIEWD

#33 US22_HarmonisationCSS
  client/src/pages/BonusGame/BonusGame.css
  client/src/pages/BonusGame/BonusGame.tsx
  client/src/pages/GameOne/GameOne.css
  client/src/pages/GameOne/GameOne.tsx
  client/src/pages/GamesHome/GamesHome.tsx
  client/src/pages/NumGame/NumGame.css
  client/src/pages/NumGame/NumGame.tsx
  client/src/pages/RandomEquation/RandomEquation.css
Labels: REVIEWD

#34 S07 us24 jwt
  client/src/pages/LoginForm/LoginForm.tsx
  client/src/pages/SignUpForm/SignUpForm.css
  client/src/pages/SignUpForm/SignUpForm.tsx
  server/package.json
  server/src/app.ts
  server/src/middlewares/authMiddleware.ts
  server/src/middlewares/jwtMiddleware.ts
  server/src/modules/item/auth/authAction.ts
  server/src/router.ts
Labels: CORRECTIONS_DONE
