Repository WildCodeSchool-2024-09/JS-RemoteFR-Crew404-Mathemagie, pull requests merged in 2025-02, with the labels that each got.

#38 US25 lier avatar
  client/src/main.tsx
  client/src/pages/Avatar/Avatar.tsx
  client/src/pages/BonusGame/BonusGame.tsx
  client/src/pages/GamesHome/GamesHome.tsx
  client/src/pages/LevelGame1/LevelGame1.tsx
  server/src/modules/user/userActions.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
Labels: REVIEWD

#42 S08_US_28_HeaderMAJ_Avatar
  client/src/App.css
  client/src/App.tsx
  client/src/main.tsx
  client/src/pages/Avatar/Avatar.tsx
  client/src/pages/GamesHome/GamesHome.css
  client/src/pages/GamesHome/GamesHome.tsx
Labels: REVIEWD

#43 dashboard front check
  client/src/main.tsx
  client/src/pages/DashBoard/DashBoard.css
  client/src/pages/DashBoard/DashBoard.tsx
Labels: REVIEWD

#45 S08 us31 back dash
  client/package.json
  client/public/home.png
  client/src/App.css
  client/src/App.tsx
  client/src/pages/Avatar/Avatar.tsx
  client/src/pages/Context/AvatarContext.tsx
  client/src/pages/Context/UserContext.tsx
  client/src/pages/DashBoard/DashBoard.css
  client/src/pages/DashBoard/DashBoard.tsx
  client/src/pages/GamesHome/GamesHome.tsx
  server/database/schema.sql
  server/src/modules/user/userActions.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
Labels: CHANGE_REQUESTED, CORRECTIONS_DONE

#51 S09 us30 finition
  client/src/App.tsx
  client/src/main.tsx
  client/src/pages/Avatar/avatar.css
  client/src/pages/Contact/Contact.css
  client/src/pages/Contact/Contact.tsx
  client/src/pages/Context/AuthContext.tsx
  client/src/pages/DashBoard/DashBoard.css
  client/src/pages/DashBoard/DashBoard.tsx
  client/src/pages/ForgotPassword/ForgotPassword.css
  client/src/pages/ForgotPassword/ForgotPassword.tsx
  client/src/pages/LoginForm/LoginForm.css
  client/src/pages/LoginForm/LoginForm.tsx
  client/src/pages/Score/Score.tsx
  client/src/pages/SignUpForm/SignUpForm.css
  server/database/schema.sql
  server/src/app.ts
  server/src/modules/item/auth/authAction.ts
  server/src/modules/item/auth/authRepository.ts
Labels: REVIEWD

#52 dashbord css + css numgame
  client/src/pages/DashBoard/DashBoard.css
  client/src/pages/DashBoard/DashBoard.tsx
  client/src/pages/NumGame/NumGame.css
  client/src/pages/NumGame/NumGame.tsx
Labels: REVIEWD

#53 Us33 setup addscore
  client/src/Context/AvatarContext.tsx
  client/src/Context/UserContext.tsx
  client/src/main.tsx
  client/src/pages/CarGame/CarGame.tsx
  client/src/pages/DashBoard/DashBoard.tsx
  client/src/pages/GameOne/GameOne.tsx
  client/src/pages/LevelGame1/LevelGame1.css
  client/src/pages/LevelGame1/LevelGame1.tsx
  client/src/pages/LevelGame2/LevelGame2.tsx
  client/src/pages/NumGame/NumGame.tsx
  client/src/pages/UpdateAvatar/UpdateAvatar.tsx
  client/src/pages/UpdateAvatar/updateAvatar.css
  client/src/types/types.ts
  server/database/schema.sql
  server/src/modules/user/userActions.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
Labels: CORRECTIONS_DONE, REVIEWD

#57 dashboard amelioration
  client/src/pages/DashBoard/DashBoard.css
  client/src/pages/DashBoard/DashBoard.tsx
Labels: CONFLICTS_RESOLVED, REVIEWD
